name: CD

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Install dependencies
        run: npm install

      - name: Add user to NPM
        run: npm adduser $NPM_USERNAME $NPM_TOKEN $NPM_EMAIL

      - name: Publish package
        run: npm publish
