name: CI

on: [workflow_call, workflow_dispatch, pull_request]

jobs:
  validate-ts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Validate TS
        run: npx tsc --noEmit
