name: Increment Version

on: [workflow_call, workflow_dispatch, pull_request]

jobs:
  validate-ts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Increment patch number
        run: npm version patch >> $VERSION
        id: increment

      - name: Stage changes
        run: git add package.json

      - name: Commit changes
        run: git commit -m "Increment patch to ${{ steps.increment.outputs.VERSION }}"

      - name: Push changes
        run: git push
