name: Increment Version

on: [workflow_call, workflow_dispatch, pull_request]

jobs:
  increment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Increment patch number
        run: npm version patch >> "$GITHUB_OUTPUT"
        id: increment

      - name: Stage changes
        run: git add package.json

      - name: Set name
        run: git config user.name "Gearbox Bot"

      - name: Set email
        run: git config user.email "gearbox@decaturrobotics.org"

      - name: Commit changes
        run: git commit -m "Increment patch to ${{ steps.increment.outputs.* }}"

      - name: Push changes
        run: git push
