name: Increment Version

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  increment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: $GITHUB_HEAD_REF

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Set name
        run: git config user.name "Gearbox Bot"

      - name: Set email
        run: git config user.email "gearbox@decaturrobotics.org"

      - name: Increment patch number
        run: npm version patch

      - name: Push changes
        run: git push
